[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[mouse]
hide_when_typing = true

[keyboard]

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

# NEW BINDING for Alt + Left Arrow (Word Backward)
[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"  # \u001b is Escape, followed by literal 'b'

# NEW BINDING for Alt + Right Arrow (Word Forward)
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"  # \u001b is Escape, followed by literal 'f'
